version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.1.1
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
  # This "container" is a workaround to pre-create topics
  # https://github.com/confluentinc/examples/blob/f854ac008952346ceaba0d1f1a352788f0572c74/microservices-orders/docker-compose.yml#L182-L215
  kafka-setup:
    image: confluentinc/cp-kafka:5.1.1
    hostname: kafka-setup
    container_name: kafka-setup
    depends_on:
      - kafka
      - zookeeper
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                 cub kafka-ready -b kafka:9092 1 30 && \
                 kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic events-message-v1 && \
                 sleep 30'"
    environment:
      # The following settings are listed here only to satisfy the image's requirements.
      # We override the image's `command` anyways, hence this container will not start a broker.
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

#  database:
#    image: postgres:12.5-alpine
#    networks:
#      - quints
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: quints
#      POSTGRES_PASSWORD: quints
#      POSTGRES_DB: quints
#
#  kafka:
#    image: bitnami/kafka:latest
#    networks:
#      - quints
#    ports:
#      - 9092:9092
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      ALLOW_PLAINTEXT_LISTENER: "yes"
#      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#    depends_on:
#      - zookeeper

#  rabbitmq:
#    image: rabbitmq:3.8.3-management-alpine
#    networks:
#      - quints
#    ports:
#      - 5672:5672
#      - 15672:15672



#  # This "container" is a workaround to pre-create topics
#  # https://github.com/confluentinc/examples/blob/f854ac008952346ceaba0d1f1a352788f0572c74/microservices-orders/docker-compose.yml#L182-L215
#  kafka-setup:
#    image: confluentinc/cp-kafka:5.1.1
#    hostname: kafka-setup
#    container_name: kafka-setup
#    depends_on:
#      - kafka
#      - zookeeper
#    command: "bash -c 'echo Waiting for Kafka to be ready... && \
#                 cub kafka-ready -b kafka:9092 1 30 && \
#                 kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic quickstart-events && \
#                 sleep 30'"
#    environment:
#      # The following settings are listed here only to satisfy the image's requirements.
#      # We override the image's `command` anyways, hence this container will not start a broker.
#      KAFKA_BROKER_ID: ignored
#      KAFKA_ZOOKEEPER_CONNECT: ignored

#  zookeeper:
#    image: bitnami/zookeeper:latest
#    ports:
#      - 2181:2181
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: confluentinc/cp-kafka:5.1.1
#    ports:
#      - 9092:9092
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#    depends_on:
#      - zookeeper
#  # This "container" is a workaround to pre-create topics
#  # https://github.com/confluentinc/examples/blob/f854ac008952346ceaba0d1f1a352788f0572c74/microservices-orders/docker-compose.yml#L182-L215
#  kafka-setup:
#    image: confluentinc/cp-kafka:5.1.1
#    hostname: kafka-setup
#    container_name: kafka-setup
#    depends_on:
#      - kafka
#      - zookeeper
#    command: "bash -c 'echo Waiting for Kafka to be ready... && \
#                 cub kafka-ready -b kafka:9092 1 30 && \
#                 kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic quickstart-events && \
#                 sleep 30'"
#    environment:
#      # The following settings are listed here only to satisfy the image's requirements.
#      # We override the image's `command` anyways, hence this container will not start a broker.
#      KAFKA_BROKER_ID: ignored
#      KAFKA_ZOOKEEPER_CONNECT: ignored
#
##networks:
##  quints:
